name: vCore
version: '1.1.0'
main: nl.vCore.Main
api-version: '1.16'
description: A databasing plugin for User Information such as homes, bans, warnings, and warps
author: vCore Team
website: https://discord.gg/HBGdXtAj5g
commands:
  # Will be added in future updates
permissions:
  vcore.admin:
    description: Grants all vCore permissions
    default: op
  vcore.user:
    description: Basic user permissions
    default: true
